### ISSUE TITLE
Can i do this query using Graph API?

### ISSUE THREAD

**Issue by CoericK** [SammyK/FacebookQueryBuilder#13]
Hello i would like to know if there is possible to run this query using Fracebook Graph API.

Can i get ALL the Facebook Pages, when the category of the facebook page, is Actor?

For example, something like this :
```
$c = 'actor';
 $fqb->edge('pages')->fields('category', $c);
```

If it possibe to this?

**Comment by SammyK** [comment]
Hey @CoericK!

You might be able to make use of the [search feature](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.2#search) which lets you search pages on Facebook (amongst other things). But it doesn't have an option for filtering by page category. You can just search for a specific actor name for example:

```php
$res = $fqb->search('Some Actor', 'page')->get();
```

Another option might be to use [FQL](https://developers.facebook.com/docs/reference/fql/), but that feature has been deprecated and will be unavailable when Graph 2.0 unsupported is removed on [August 7, 2016](https://developers.facebook.com/docs/apps/versions/).

Wish I could offer more help but it seems like this is a limitation with the Graph API.
