### ISSUE TITLE
Debug switch?

### ISSUE THREAD

**Issue by vojtasvoboda** [SammyK/FacebookQueryBuilder#14]
Is there any debug switch, to see full answer from Graph API?

$fb = App::make('facebook-query-builder');
$fb->setAccessToken('CAAIt8ie86xwBALP1tdkYTSctlj9dBc...');
$user = $fb->search('Bill', 'user')->get();

I don't know whats wrong, because all requests returns same error "Graph returned an error response."

**Comment by SammyK** [comment]
Hey @vojtasvoboda!

In version 1.x of FQB, exceptions from the Facebook PHP SDK are re-thrown horizontally. So in your try/catch you'll need to make use of `getPrevious()` to access the exception thrown by the SDK. You can also use `getResponse()` to see the raw error response from Graph.

```php
use SammyK\FacebookQueryBuilder\FacebookQueryBuilderException;

try {
    $user = $fb->search('Bill', 'user')->get();
} catch (FacebookQueryBuilderException $e) {
    echo $e->getPrevious()->getMessage();
    // A handy way to grab the response from Graph
    var_dump($e->getResponse());
    exit;
}
```
