### ISSUE TITLE
Example on how to obtain a Page Access Token

### ISSUE THREAD

**Issue by pns2050** [SammyK/FacebookQueryBuilder#15]
Hello SammyK,

Firstly thanks for all this great work that you are putting into this.

Is it possible to show an example on how to obtain a page access token ?

What i was able to do is : 

1) Request user access token with manage_page permissions
2) Extend token to long lived one

Now i know that i have to use that token with a GET on 'me/accounts' but i just cant find out how...

Thanks!

**Comment by ijagdeepsingh** [comment]
You can obtain page access tokens using this library like this.

    // Setting The Access Token
    FQB::setAccessToken('long_lived_access_token');
    $page_tokens = $fqb->object('me/accounts')->fields('id','name')->get();
    // for checking
    die( $page_tokens->toJSON() )

**Comment by pns2050** [comment]
Thanks @ijagdeepsingh ! That worked!

**Comment by SammyK** [comment]
@ijagdeepsingh - Thanks for helping @pns2050 out on this one! :) :beers:

**Comment by ijagdeepsingh** [comment]
@SammyK Thank you for amazing library.

Any plans to support multi-id-lookup?

Currently I'm using this work around

`$get = '/?ids=' . implode(",", $selected_albums) . '&fields=id,name,count,cover_photo,from,privacy,type,created_time';`
`// get selected albums details from facebook`
` $albums_from_fb = Facebook::object($get)->get();`

**Comment by SammyK** [comment]
You're welcome @ijagdeepsingh! :)

I think the query builder will be focused to just nested requests, but can you submit a new issue for this topic of supporting multi-id-requests? I'd like to consider this before tagging 2.0 stable. :)
