### ISSUE TITLE
[Feature request] Support for multi-id-lookup

### ISSUE THREAD

**Issue by jdsingh** [SammyK/FacebookQueryBuilder#16]
A request to support multi-id-lookup.

Currently I have to use this work around to make multi-id-lookup requests.

``` php
$get = '/?ids={id-one},{id-two}&fields=id,name';
$object = Facebook::object($get)->get();
```

It would be great if you can make it this way...

``` php
$get = '/?ids={id-one},{id-two}';
$object = Facebook::object($get)->fields('id', 'name')->get();
```

or may be this way...

``` php
$object = Facebook::object('?ids')->ids->({id-one},{id-two})->fields('id', 'name')->get();
```

**Comment by SammyK** [comment]
Thanks for this @ijagdeepsingh! As we get closer to releasing the next stable version of the SDK I'm going to be finalizing v2.0 of the FQB. And I'll be considering your proposed API. So consider this one "queued up for 2.0 review". :)

**Comment by ijagdeepsingh** [comment]
Cool. Thanks for considering my request.

On Wed, Jan 28, 2015 at 9:44 PM, Sammy Kaye Powers <notifications@github.com
