### ISSUE TITLE
Save access_token to the users table?

### ISSUE THREAD

**Issue by natenrb9** [SammyK/FacebookQueryBuilder#18]
Also, I have a user logging in fine and saving all of their info (id, name, email, etc) to the DB, but it does not seem to be saving the access_token? Isn't it supposed to be? I am not sure why it isn't saving that portion in the DB...I can't tell if it is a bug, or something I need to configure?

**Comment by jagdeepsinghmundi** [comment]
You'll need to save it separately.

When you receive user's information from Facebook and save it using Model it does not contain access_token in response, that is why it isn't saving the access token.

But you can do it this way...

```php
// update access token in user's profile
$user->access_token = $token;
$user->save();
```
