### ISSUE TITLE
getGraphList() method

### ISSUE THREAD

**Issue by G-Giorgianni** [SammyK/FacebookQueryBuilder#21]
I was trying to use your pagination example without offset, but I get this error:  Call to undefined method SammyK\\FacebookQueryBuilder\\GraphCollection::getGraphList() in /var/www/html/script/request.php on line 209
I actually checked in the GraphCollection Class and I couldn't find that method. Any idea how to solve this?
This is my FQB request:

$links = $fqb->object('me/links')
->fields('id','comments','likes')
->with(['offset' => $offset,
        'since'=>1409529600])
->limit($limit)
->get();

Cheers

**Comment by SammyK** [comment]
Hey @G-Giorgianni! Which version of FQB are you using? There aren't any references to `getGraphList()` in the source code.
